name = "video-downloader"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
COBALT_URL = "https://cobalt-server.infoanuj74.workers.dev"

[[services]]
binding = "COBALT_WORKER"
service = "cobalt-server"
