name = "video-downloader"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
COBALT_API_URL = "http://localhost:9000/api/json"

[[services]]
binding = "COBALT_WORKER"
service = "cobalt-server"
