name = "video-downloader"
compatibility_date = "2026-02-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
COBALT_API_URL = "https://api.cobalt.tools/api/json"

[[durable_objects.bindings]]
name = "COBALT_SERVICE"
class_name = "CobaltContainer"
script_name = "cobalt-server"

[[services]]
binding = "COBALT_WORKER"
service = "cobalt-server"
