name = "video-downloader-app"
compatibility_date = "2026-02-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
ENVIRONMENT = "production"

[[services]]
binding = "COBALT_WORKER"
service = "cobalt-server"

[[durable_objects.bindings]]
name = "COBALT_SERVICE"
class_name = "CobaltContainer"
script_name = "cobalt-server"
