name = "cobalt-server"
main = "src/index.ts"
compatibility_date = "2026-02-21"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "COBALT_SERVICE", class_name = "CobaltContainer" }
]

[vars]
ENVIRONMENT = "production"
API_PORT = "9000"
API_URL = "http://127.0.0.1:9000"
API_NAME = "FastVideoSave-Engine"
CORS_WILDCARD = "1"
# Webshare Rotating Proxy (Production extraction)
API_EXTERNAL_PROXY = "http://xcjkkris-rotate:e8pk5mmdnsgt@p.webshare.io:80"

[[containers]]
name = "cobalt-worker-v10"
class_name = "CobaltContainer"
image = "./Dockerfile"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CobaltContainer"]
